input {
    beats {
        port => 5044
    }
}
filter {
  # --- Yii2 логи ---
  if [fields][service] =~ "yii2" and [fields][service] !~ "auth" {
    grok {
      match => { 
        "message" => "%{TIMESTAMP_ISO8601:log_time} \[%{DATA:user}\]\[%{DATA:ip}\]\[%{DATA:session}\]\[%{LOGLEVEL:level}\]\[%{DATA:category}\] %{GREEDYDATA:msg}" 
      }
      tag_on_failure => ["_yii2_grok_fail"]
    }
    date {
      match => [ "log_time", "yyyy-MM-dd HH:mm:ss" ]
      target => "@timestamp"
      timezone => "Europe/Moscow"
    }
    mutate {
      remove_field => [ "log_time", "user", "ip", "session" ]
    }
  }
  
  # --- Syslog / Auth.log ---
  else if [fields][service] == "yii2_test_auth" {
    # Стандартный syslog-формат:
    # May  3 00:37:40 hostname sshd[pid]: message
    
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"
      }
      tag_on_failure => ["_syslog_grok_fail"]
    }
    
    # Парсим время (добавляем текущий год, т.к. syslog его не содержит)
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      target => "@timestamp"
      timezone => "Europe/Moscow"
    }
    
    # Добавляем год к @timestamp, если он потерялся
    if [syslog_timestamp] and ![@timestamp] {
      mutate {
        add_field => { "temp_year" => "%{+YYYY}" }
      }
    }
    
    # Очищаем временные поля
    mutate {
      remove_field => [ "syslog_timestamp", "temp_year" ]
    }
  }
}
output {
    stdout {   
        codec => rubydebug 
    }
    elasticsearch {
        hosts =>  ["http://elasticsearch:9200"]
        index => "app-%{[fields][service]}-%{+YYYY.MM.dd}"
        user => "elastic"            
        password => "POT654kds" 
        manage_template => false

    }
}
